name       : python-pytest-mock
version    : 3.5.1
release    : 7
source     :
    - https://github.com/pytest-dev/pytest-mock/archive/v3.5.1.tar.gz : e17da6e2aba3f34b5b6622ccd7f8c95c7271a34287e60bb9703c90925216a7ce
license    : MIT
component  : programming.python
summary    : Thin-wrapper around the mock package for easier use with py.test
description: |
    This plugin installs a mocker fixture which is a thin-wrapper around the patching API provided by the mock package, but with the benefit of not having to worry about undoing patches at the end of a test:
builddeps  :
    - python-mock
    - python-pytest
    - python-setuptools-scm
rundeps    :
    - python-mock
    - python-pytest
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v -k 'not test_standalone_mock'  --assert=plain
