name       : python-pytest-mock
version    : 3.11.1
release    : 12
source     :
    - https://github.com/pytest-dev/pytest-mock/archive/refs/tags/v3.11.1.tar.gz : f0a7a047c5eca74ceb52008b2b07f962338a07425b9ea41079e43be9e82aba8b
homepage   : https://github.com/pytest-dev/pytest-mock
license    : MIT
component  : programming.python
summary    : Thin-wrapper around the mock package for easier use with py.test
description: |
    This plugin installs a mocker fixture which is a thin-wrapper around the patching API provided by the mock package, but with the benefit of not having to worry about undoing patches at the end of a test.
builddeps  :
    - python-pytest-asyncio # check
    - python-setuptools-scm
rundeps    :
    - python-pytest
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v -k 'not test_standalone_mock'  --assert=plain
