name       : python-pytest-mock
version    : 1.11.2
release    : 4
source     :
    - https://github.com/pytest-dev/pytest-mock/archive/v1.11.2.tar.gz : 2987c592016125c868706d739540ce49d7c245bf3a0a8f44f78d3ef255bdae4b
license    : MIT
component  : programming.python
summary    : Thin-wrapper around the mock package for easier use with py.test
description: |
    This plugin installs a mocker fixture which is a thin-wrapper around the patching API provided by the mock package, but with the benefit of not having to worry about undoing patches at the end of a test:
builddeps  :
    - python-mock
    - python-pytest
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - python-mock
    - python-pytest
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -v  --assert=plain
    %python3_test py.test3 -v -k 'not test_standalone_mock'  --assert=plain
