name       : python-pytest-mock
version    : 3.6.1
release    : 9
source     :
    - https://github.com/pytest-dev/pytest-mock/archive/refs/tags/v3.6.1.tar.gz : f4cbdd4315a44a40cb824cde8291c3d43eb046d2cc4113c5c330dc9805f11440
license    : MIT
component  : programming.python
summary    : Thin-wrapper around the mock package for easier use with py.test
description: |
    This plugin installs a mocker fixture which is a thin-wrapper around the patching API provided by the mock package, but with the benefit of not having to worry about undoing patches at the end of a test:
builddeps  :
    - python-mock
    - python-pytest
    - python-setuptools-scm
rundeps    :
    - python-mock
    - python-pytest
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test py.test3 -v -k 'not test_standalone_mock'  --assert=plain
